- hosts: webservers

  vars:
    root_dir: /usr/share/nginx/html
    msg: "This is server {{ ansible_hostname }}!"
    str: "{{ msg | upper }}"
    date: "{{ ansible_date_time['iso8601'] }}"

  tasks:
    - name: Show host name
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }}"

    - name: copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes


