- hosts: all
  tasks:
    - name: update apt
      ansible.builtin.apt:
        name: apt
        state: present
        update_cache: yes
      become: yes

#    - name: install python3
#      ansible.builtin.apt:
#        name: python3
#        state: present
#        update_cache: yes
#      become: yes

    - name: install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes

#    - name: install python3-pip
#      ansible.builtin.apt:
#        name: python3-pip
#        state: present
#        update_cache: yes
#        cache_valid_time: 604800 # 1 week
#      become: yes


#    - name: install docker
#      ansible.builtin.pip:
#        name: docker
#        state: present
#      become: yes

    - community.docker.docker_container:
        name: app
        # Обязательно указываем тег, который хотим деплоить
        # Если образа на сервере нет, Ansible его автоматически скачает
        image: "dementy/devops-example-app:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор Docker его перезапустит
        restart_policy: always
        # Запускаем, если не запущен
        state: started
        # Делаем доступным снаружи
        ports:
          - 3000:3000
        env: # Настраиваем
          NODE_ENV: production
          SERVER_MESSAGE: "Test"
      become: yes
